### ISSUE TITLE
Design a logo for Elixir Ethers

### ISSUE THREAD

**Issue by alisinabh** [alisinabh/elixir_ethers#1]
As an open source project, It is good to have a logo designed for the project. Here are some of the guidelines for the logo:

 - It must resemble and have an element of web3/blockchain/ethereum.
 - It must imply Elixir either with the droplet shape of Elixir logo, it's colour or any other characteristics of it.
 - It must be original and not a copy.

**Comment by Mythx-is-Dead** [comment]
stumbled on this github & was bored so heres a concept homie, https://imgur.com/a/HHfCQjm

**Comment by hamzaghz** [comment]
hello @alisinabh i tried to submit my request to start the work, but in vain. so i had this proposition if you wanna  accept its draft 
![elixir0](https://user-images.githubusercontent.com/60444350/233872486-0c7b543f-19bc-456d-9cdf-fb492435af55.svg)

**Comment by alisinabh** [comment]
Hey Guys, Thank you for your submissions. Unfortunately we cannot actually use the elixir logo inside this logo at all. However as said in the original description something that resembles elixir (like a droplet or the color) can be used.

**Comment by web3files** [comment]
![_3a751d27-c489-46a9-a232-abb77b58ac05](https://user-images.githubusercontent.com/97182070/234331921-0e97ef02-21e9-44ac-8f6c-67daaef9c3c8.png)
![_05e35afe-eb03-4b6f-bafa-03158a317a52](https://user-images.githubusercontent.com/97182070/234331944-d654de0d-4018-4a3f-b431-133c3989bb4c.png)
![enhancedRemoved](https://user-images.githubusercontent.com/97182070/234331978-859d0387-eb9e-4388-bd95-10ff00350b7a.png)
![latestremoved](https://user-images.githubusercontent.com/97182070/234332081-db53ed2b-7c43-47b8-b6aa-a1bed45b9373.png)
![_1f42c7c5-ab29-49eb-8a69-8e231ce58dea](https://user-images.githubusercontent.com/97182070/234332167-d8bfbf08-ec75-457b-893b-5009b5bc340b.jpg)
![_5e0d7552-a926-4052-bec7-8b51d29d39da (2)](https://user-images.githubusercontent.com/97182070/234334265-778afa03-0d46-406b-b9f6-58da10a32e39.jpg)
![_77bcfbde-3147-41f1-8d32-ec47008d9155](https://user-images.githubusercontent.com/97182070/234334294-0413394d-d896-42a6-a342-ac162623f17a.jpg)
![_92dad55d-3dec-4fa7-b610-a3da632bd128 (2)](https://user-images.githubusercontent.com/97182070/234334325-5104ab3f-81ad-4057-86db-bf0ac38e65c2.jpg)
![_845b2bb2-6d69-4382-8dfe-0b60534deb7b (2)](https://user-images.githubusercontent.com/97182070/234334336-9e0960df-3256-46e6-a54f-64ec7255488f.jpg)
![_875f4db8-ab0a-48e7-9bd7-45a684b01ffb (2)](https://user-images.githubusercontent.com/97182070/234334350-93e8c0cd-f333-4f79-a34a-e6c553fdd2d4.jpg)
![_35799c6b-be9a-4c99-b9e1-69d3a8be13fc (2)](https://user-images.githubusercontent.com/97182070/234334355-b36f5f32-a94e-4903-bae8-c45f5dec5a97.jpg)
![_4426755d-4482-4dc7-bc30-9a8586a9afb5 (2)](https://user-images.githubusercontent.com/97182070/234334523-3dffa998-cfea-4bd3-b805-2745c65aeab8.jpg)
![_aa56cef7-c5b2-4c00-85e6-52bf94095e31 (2)](https://user-images.githubusercontent.com/97182070/234334598-cb6c2f65-040c-4730-8d77-b828e5bb7149.jpg)
![_e4695a3f-e6e0-40df-bf23-9c13ede83311 (2)](https://user-images.githubusercontent.com/97182070/234334671-b2f46712-df84-47dd-a10e-ab022cf7ec9c.jpg)
![_e1622436-9095-4eb9-b690-9bf905647011 (2)](https://user-images.githubusercontent.com/97182070/234334679-ec485670-6c4f-44e7-98ec-8ae625e6af0f.jpg)
![_eaebd9b7-145a-40d7-9b53-c10db09fcc79 (2)](https://user-images.githubusercontent.com/97182070/234334687-f1d0fa80-8c6d-4abb-bd97-1a392870739f.jpg)
Created with love and passion . 
Here is my address if you wanna support my work : 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

**Comment by web3files** [comment]
![_3a751d27-c489-46a9-a232-abb77b58ac05](https://user-images.githubusercontent.com/97182070/234331921-0e97ef02-21e9-44ac-8f6c-67daaef9c3c8.png)
![_05e35afe-eb03-4b6f-bafa-03158a317a52](https://user-images.githubusercontent.com/97182070/234331944-d654de0d-4018-4a3f-b431-133c3989bb4c.png)
![enhancedRemoved](https://user-images.githubusercontent.com/97182070/234331978-859d0387-eb9e-4388-bd95-10ff00350b7a.png)
![latestremoved](https://user-images.githubusercontent.com/97182070/234332081-db53ed2b-7c43-47b8-b6aa-a1bed45b9373.png)
![_1f42c7c5-ab29-49eb-8a69-8e231ce58dea](https://user-images.githubusercontent.com/97182070/234332167-d8bfbf08-ec75-457b-893b-5009b5bc340b.jpg)
![_5e0d7552-a926-4052-bec7-8b51d29d39da (2)](https://user-images.githubusercontent.com/97182070/234334265-778afa03-0d46-406b-b9f6-58da10a32e39.jpg)
![_77bcfbde-3147-41f1-8d32-ec47008d9155](https://user-images.githubusercontent.com/97182070/234334294-0413394d-d896-42a6-a342-ac162623f17a.jpg)
![_92dad55d-3dec-4fa7-b610-a3da632bd128 (2)](https://user-images.githubusercontent.com/97182070/234334325-5104ab3f-81ad-4057-86db-bf0ac38e65c2.jpg)
![_845b2bb2-6d69-4382-8dfe-0b60534deb7b (2)](https://user-images.githubusercontent.com/97182070/234334336-9e0960df-3256-46e6-a54f-64ec7255488f.jpg)
![_875f4db8-ab0a-48e7-9bd7-45a684b01ffb (2)](https://user-images.githubusercontent.com/97182070/234334350-93e8c0cd-f333-4f79-a34a-e6c553fdd2d4.jpg)
![_35799c6b-be9a-4c99-b9e1-69d3a8be13fc (2)](https://user-images.githubusercontent.com/97182070/234334355-b36f5f32-a94e-4903-bae8-c45f5dec5a97.jpg)
![_4426755d-4482-4dc7-bc30-9a8586a9afb5 (2)](https://user-images.githubusercontent.com/97182070/234334523-3dffa998-cfea-4bd3-b805-2745c65aeab8.jpg)
![_aa56cef7-c5b2-4c00-85e6-52bf94095e31 (2)](https://user-images.githubusercontent.com/97182070/234334598-cb6c2f65-040c-4730-8d77-b828e5bb7149.jpg)
![_e4695a3f-e6e0-40df-bf23-9c13ede83311 (2)](https://user-images.githubusercontent.com/97182070/234334671-b2f46712-df84-47dd-a10e-ab022cf7ec9c.jpg)
![_e1622436-9095-4eb9-b690-9bf905647011 (2)](https://user-images.githubusercontent.com/97182070/234334679-ec485670-6c4f-44e7-98ec-8ae625e6af0f.jpg)
![_eaebd9b7-145a-40d7-9b53-c10db09fcc79 (2)](https://user-images.githubusercontent.com/97182070/234334687-f1d0fa80-8c6d-4abb-bd97-1a392870739f.jpg)
Created with love and passion . 
Here is my address if you wanna support my work : 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

**Comment by web3files** [comment]
pls ask if you need something

**Comment by web3files** [comment]
![_77bcfbde-3147-41f1-8d32-ec47008d9155 (2)](https://user-images.githubusercontent.com/97182070/234336057-ed039690-1435-4aa7-adf0-018dedcadcda.jpg)

**Comment by sebasarriaza** [comment]
I have submitted a pull request that adds 28 logo options to the 'public/logos' folder in the repository. These logos were designed to incorporate web3/blockchain/Ethereum elements and the Elixir droplet shape. Please review and let me know if any changes are needed
