### ISSUE TITLE
Implement Multicall functionality

### ISSUE THREAD

**Issue by alisinabh** [alisinabh/elixir_ethers#23]
Often users need to call multiple functions on contracts. It would be useful to have a batch function which handles all the call actions in a single rpc request.

**Comment by BlazeWasHere** [comment]
Was about to make a feature request for this! Will work on this over the weekend and send over a PR.

I think under the hood, [Multicall3](https://multicall3.com) should be used to batch multiple calls into a single rpc request.

Perhaps some usage like this?
```elixir
[ContractA.a(), ContractB.b()]
|> Multicall3.aggregate()
|> Ethers.send!()
```

I guess the first task here is converting `Contract.a()` to `{Ethers.Types.t_address(), binary()}`. However, `TxData.default_address` can be `nil`, and the overrided `to` in `Ethers.send/2` will not work here. A way around would be to allow for optional addresses, so something like:
```elixir
[
  ContractAWithDefaultAddress.a(),
  { ContractB.b(), to: "0x..." }
] 
|> Multicall3.aggregate()
|> Ethers.send!()
```

**Comment by alisinabh** [comment]
Thank you @BlazeWasHere,

Actually I have been thinking about this and decided to divide this ticket into two as follows.

One is as you suggested, Implementing (different versions of) Muticall. It can be done either as part of Ethers or an additional library. For now I think it makes sense to include it in Ethers since this is a very widely used trick across the spectrum.

The other one was actually implementing batching RPC requests together using [Ethereumex batch_request](https://github.com/mana-ethereum/ethereumex#batch-requests). This is a bit more cumbersome and required breaking down `Ethers.call/2`, `Ethers.send/2` and other functions in the Ethers module to pre-process and post-process steps to re-use the implementation in a new `Ethers.batch/?` function.

You are very welcome to work on either or both. I have created a new issue for the batch request scenario. This one will be for the Multicall.

I would suggest that we implement Multicall in a new module (e.g. `Ethers.Multicall`) but please have a look and let me know what you think.

**Comment by BlazeWasHere** [comment]
Sounds good @alisinabh I will work on `Ethers.Multicall` which will implement `aggregate/2` and `aggregate/3` which will be able to passed onto `Ethers.call/2` by the user
