### ISSUE TITLE
Invalid function reference in the documentation

### ISSUE THREAD

**Issue by masudme09** [alisinabh/elixir_ethers#61]
I found one invalid function call reference while using the documentation to test with Ethers. 

![image](https://github.com/alisinabh/elixir_ethers/assets/50353230/1e0e1b30-cb35-492d-b705-bed7ed54d5e3)

```Ethers.Contract.call()``` is not available under the module ```Ethers.Contract```, instead, its available under module ```Ethers```.

So, what can be the solution here? Just fix the documentation or add ```Ethers.Contract.call()``` function by delegating it to ```Ethers.call()```?  I can make the pull request with the suggested solution. @alisinabh

**Comment by alisinabh** [comment]
Hey @masudme09,

Great catch! I believe we should fix the documentation. As you guessed `Ethers.Contract.call/2` is now history and replaced with `Ethers.call/2`.

A PR is very welcome!

**Comment by masudme09** [comment]
Added a PR with small convenience texts. 

https://github.com/alisinabh/elixir_ethers/pull/62
